"use client";
import localFont from "next/font/local";
import store from "@/redux/store/store";
import { Provider } from "react-redux";
import { Notification } from "@/notification/Notification";
import { AuthProvider } from "@/context/AuthContext";
import { AbilityProvider } from "@/context/AbilityContext";
import { GetUserRoles } from "./api/role/GetRoles";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          {/* Ensure user context is valid, could be dynamic from auth */}
            <AuthProvider>
          <AbilityProvider>
              <Notification />
              {children}
          </AbilityProvider>
            </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
